apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: provision-pipeline
spec:
  finally:
    - name: release-lease-on-failure
      when:
        - input: "$(tasks.provision-ti.status)"
          operator: in
          values: ["Failed", "Cancelled"]
      params:
        - name: jmp-lease-id
          value: $(tasks.get-lease.results.jmp-lease-id)
        - name: client-name
          value: $(params.client-name)
      taskRef:
        kind: Task
        name: jumpstarter-release-lease
      workspaces:
        - name: jumpstarter-client-secret
          workspace: jumpstarter-client-secret

    - name: release-lease-on-completion
      when:
        - input: "$(context.pipelineRun.status)"
          operator: notin
          values: ["Failed"]
        - input: "$(params.debug-mode)"
          operator: notin
          values: ["true"]
      params:
        - name: jmp-lease-id
          value: $(tasks.get-lease.results.jmp-lease-id)
        - name: client-name
          value: $(params.client-name)
      taskRef:
        kind: Task
        name: jumpstarter-release-lease
      workspaces:
        - name: jumpstarter-client-secret
          workspace: jumpstarter-client-secret

  params:
    - name: hw-target
      type: string
      default: j784s4evm
    - description: A list of label exporters in the format key=value
      name: exporter-labels
      type: array
    - name: image
      description: OS image to provision with
      type: string
    - description: Jumpstarter client name to use
      name: client-name
      type: string
      default: "default"
    - name: debug-mode
      description: If true, lease won't be released on success or cancellation. Lease WILL be released on FAILURE regardless of this flag.
      type: string
      default: "false"
    - name: skip-provision
      description: If true, skip the provisioning step
      type: string
      default: "false"

  tasks:
    - name: get-lease
      params:
        - name: client-name
          value: $(params.client-name)
        - name: exporter-labels
          value: ["$(params.exporter-labels[*])"]
      taskRef:
        kind: Task
        name: jumpstarter-get-lease
      workspaces:
        - name: jumpstarter-client-secret
          workspace: jumpstarter-client-secret

    - name: provision-ti
      when:
        - input: "$(params.hw-target)"
          operator: in
          values: ["j784s4evm"]
        - input: "$(params.skip-provision)"
          operator: notin
          values: ["true"]
      params:
        - name: client-name
          value: $(params.client-name)
        - name: jmp-lease-id
          value: $(tasks.get-lease.results.jmp-lease-id)
        - name: image
          value: $(params.image)
      runAfter:
        - get-lease
      taskRef:
        kind: Task
        name: jumpstarter-provision-board-ti
      workspaces:
        - name: jumpstarter-client-secret
          workspace: jumpstarter-client-secret
        - name: shared-workspace
          workspace: shared-workspace

  workspaces:
    - name: jumpstarter-client-secret
    - name: shared-workspace
